server:
  port: 8092

#xxl-job 配置信息
xxl:
  job:
    admin:
      addresses: http://localhost:8090/xxl-job-admin
    executor:
      appName: noah-job
      ip:
      port: 9097
      logPath: /data/applogs/xxl-job/jobhandler
      logRetentionDays: -1
    accessToken:

#spring:
#  #redis 配置信息
#  redis:
#    host: 127.0.0.1
#    port: 6379

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.103.157:3306/ccty?useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Zan54321@
    hikari:
      minimum-idle: 5
      maximum-pool-size: 1000
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 30000
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ccty.noah.domain.database
  configuration:
    map-underscore-to-camel-case: true

